
function[] = equil(reserve)
cd ('/media/fikri02/Data/MPA_targets/mains')
load ('../output/trade_off_scenarios_results.mat')

X1 = [];X2 = [];X3 = [];X4 = [];
Y1 = [];Y2 = [];Y3 = [];Y4 = [];

for i = 1: length(trade_off_results.catch_long{1,6})
if trade_off_results.catch_long{1,6}(i,3) == 0 && (trade_off_results.catch_long{1,6}(i,1)+ trade_off_results.catch_long{1,6}(i,2)) == 1
    X1 = [X1 trade_off_results.catch_long{1,6}(i,2)];
    Y1 = [Y1 trade_off_results.catch_long{1,6}(i,6)];
    
    X2 = [X2 trade_off_results.catch_long{2,6}(i,2)];
    Y2 = [Y2 trade_off_results.catch_long{2,6}(i,6)];
    
    X3 = [X3 trade_off_results.catch_long{3,6}(i,2)];
    Y3 = [Y3 trade_off_results.catch_long{3,6}(i,6)];
    
    X4 = [X4 trade_off_results.catch_long{4,6}(i,2)];
    Y4 = [Y4 trade_off_results.catch_long{4,6}(i,6)];
else
end
end
    
%find long-term catch that is generated by 30% marine reserve size
 A = round(Y1(X1==reserve),2) %long_catch_parrotfish
 B = round(Y2(X2==reserve),2) %long_catch_snapper
 C = round(Y3(X3==reserve),2) %long_catch_grouper
 D = round(Y4(X4==reserve),2) %long_catch_rabbitfish

%%Find equivalence MPA design for long-term catch above
a = []; b = []; c = []; d = [];% a,b,c,d consiss of 4 columns
%1st NMPA coverage, 2nd reserve coverage, 3rd FMPA coverage, 4th fishing
%effort reduction
for i = 1: size(trade_off_results.catch_long,2)
  for j = 1: size(trade_off_results.catch_long{2,1},1)
            if round(trade_off_results.catch_long{1,i}(j,6),2) == A && trade_off_results.catch_long{1,i}(j,2) <0.5
                a = [a; trade_off_results.catch_long{1,i}(j,1:3) 1-((i-1)/10)];
            else
            end
  end
end

for i = 1: size(trade_off_results.catch_long,2)
  for j = 1: size(trade_off_results.catch_long{2,1},1)
            if round(trade_off_results.catch_long{2,i}(j,6),2) == B && trade_off_results.catch_long{2,i}(j,2) <1.0
                b = [b; trade_off_results.catch_long{2,i}(j,1:3) 1-((i-1)/10)];
            else
            end
  end
end

for i = 1: size(trade_off_results.catch_long,2)
  for j = 1: size(trade_off_results.catch_long{2,1},1)
            if round(trade_off_results.catch_long{3,i}(j,6),2) == C && trade_off_results.catch_long{3,i}(j,2) <1.0
                c = [c; trade_off_results.catch_long{3,i}(j,1:3) 1-((i-1)/10)];
            else
            end
  end
end

for i = 1: size(trade_off_results.catch_long,2)
  for j = 1: size(trade_off_results.catch_long{2,1},1)
            if round(trade_off_results.catch_long{4,i}(j,6),2) == D && trade_off_results.catch_long{4,i}(j,2) <1.0
                d = [d; trade_off_results.catch_long{4,i}(j,1:3) 1-((i-1)/10)];
            else
            end
  end
end

%% Snapper plot
b_50 = []; b_30 = []; b_10 = [];

for i = 1: size(b,1)
    if round(b(i,4),2) == 0.50
        b_50 = [b_50 ;b(i,:)];
    elseif round(b(i,4),2) == 0.30
        b_30 = [b_30 ;b(i,:)];
    elseif round(b(i,4),2) == 0.10
        b_10 = [b_10 ;b(i,:)];
    else
    end
end

b_50(:,5) = (b_50(:,2)+ b_50(:,3))./(b_50(:,1)+ b_50(:,2)+ b_50(:,3));% MPA proportion over the seascape
b_50(:,6) =  b_50(:,3)./(b_50(:,1)+ b_50(:,2)+ b_50(:,3));% FMPA proportion over the seascape
b_50(:,7) =  b_50(:,3)./(b_50(:,2)+ b_50(:,3));% FMPA proportion over the MPA
b_50(:,8) =  b_50(:,2)./(b_50(:,2)+ b_50(:,3));% reserve proportion over the MPA

b_30(:,5) = (b_30(:,2)+ b_30(:,3))./(b_30(:,1)+ b_30(:,2)+ b_30(:,3));% MPA proportion over the seascape
b_30(:,6) =  b_30(:,3)./(b_30(:,1)+ b_30(:,2)+ b_30(:,3));% FMPA proportion over the seascape
b_30(:,7) =  b_30(:,3)./(b_30(:,2)+ b_30(:,3));% FMPA proportion over the MPA
b_30(:,8) =  b_30(:,2)./(b_30(:,2)+ b_30(:,3));% reserve proportion over the MPA

b_10(:,5) = (b_10(:,2)+ b_10(:,3))./(b_10(:,1)+ b_10(:,2)+ b_10(:,3));% MPA proportion over the seascape
b_10(:,6) =  b_10(:,3)./(b_10(:,1)+ b_10(:,2)+ b_10(:,3));% FMPA proportion over the seascape
b_10(:,7) =  b_10(:,3)./(b_10(:,2)+ b_10(:,3));% FMPA proportion over the MPA
b_10(:,8) =  b_10(:,2)./(b_10(:,2)+ b_10(:,3));% reserve proportion over the MPA
figure('Name','FMPA vs reserve - snapper')
scatter(b_50(:,3),b_50(:,2),150,'ro','filled','MarkerEdgeColor','k','LineWidth',1.5)
hold on
scatter(b_30(:,3),b_30(:,2),80,'g^','filled','MarkerEdgeColor','k','LineWidth',1.5)
scatter(b_10(:,3),b_10(:,2),20,'bs','filled','MarkerEdgeColor','k','LineWidth',1.5)
xlabel('FMPA coverage (%)')
ylabel('Reserve coverage(%)')

xticks(0:0.1:1)
xticklabels({'0', '10','20','30','40','50','60','70','80','90','100'})
xlim([0 1])
ylim([0 0.5])
yticks(0:0.05:1.0)
yticklabels({'0', '5','10','15','20','25','30','35','40','45','50','55','60','65','70','75','80','85','90','95','100'})
legend1 = legend(gca,'show',{'50','30','10'});
set(legend1,'Location','northeast');
title(legend1,'Effort reductions (%)');


clc
clear
end
